# Generated by Django 3.1.3 on 2020-11-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('lease', 'For Lease'), ('sale', 'For Sale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type_of_home',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('family house', 'Single family house'), ('town house', 'Town house'), ('condo', 'Condo')], max_length=30),
        ),
    ]
