# Generated by Django 3.1.3 on 2020-12-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20201130_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Lot size (Acres)'),
        ),
    ]
