# Generated by Django 3.1.3 on 2020-12-10 05:03

from django.db import migrations, models
from homeplace.listings import validators


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20201209_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[('', 'Bedrooms (All)'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
