# Generated by Django 3.1.3 on 2020-12-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamMembers',
        ),
    ]
